// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/open-suite/authorization/internal/modules/health"
	"github.com/open-suite/authorization/internal/modules/health/controllers"
	"github.com/open-suite/authorization/internal/modules/health/repositories"
	"github.com/open-suite/authorization/internal/modules/health/services"
	"github.com/open-suite/authorization/internal/modules/releasenotes"
	controllers2 "github.com/open-suite/authorization/internal/modules/releasenotes/controllers"
	repositories2 "github.com/open-suite/authorization/internal/modules/releasenotes/repositories"
	services2 "github.com/open-suite/authorization/internal/modules/releasenotes/services"
	"github.com/open-suite/authorization/internal/platform/config"
	"github.com/open-suite/authorization/internal/platform/database"
	"github.com/open-suite/authorization/internal/platform/i18n"
	"github.com/open-suite/authorization/internal/platform/redis"
	"github.com/open-suite/authorization/internal/shared/response"
)

// Injectors from wire.go:

func Initialize(ctx context.Context) (*App, error) {
	configConfig := config.Load()
	logger, err := ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	translator, err := i18n.NewTranslator()
	if err != nil {
		return nil, err
	}
	sender := response.NewSender(translator, logger)
	databaseDatabase, err := database.New(ctx, configConfig, logger)
	if err != nil {
		return nil, err
	}
	redisRedis, err := redis.New(ctx, configConfig, logger)
	if err != nil {
		return nil, err
	}
	healthRepository := repositories.NewHealthRepository(databaseDatabase, redisRedis)
	healthService := services.NewHealthService(healthRepository, logger)
	healthController := controllers.NewHealthController(healthService, sender, logger)
	healthModuleImpl := health.NewHealthModule(healthController)
	releaseNoteRepository := repositories2.NewReleaseNoteRepository(databaseDatabase, logger)
	releaseNoteService := services2.NewReleaseNoteService(releaseNoteRepository, logger)
	releaseNoteController := controllers2.NewReleaseNoteController(releaseNoteService, sender, logger)
	releaseNoteModuleImpl := releasenotes.NewReleaseNoteModule(releaseNoteController)
	v := ProvideModules(healthModuleImpl, releaseNoteModuleImpl)
	app := New(configConfig, logger, sender, databaseDatabase, redisRedis, v)
	return app, nil
}
